version: "3.7"
services:
    app:
        build:
            args:
                user: default
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: ldevsalesmanager
        container_name: ldevsalesmanager-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - ldevsalesmanager
    nginx:
        image: nginx:1.17-alpine
        container_name: ldevsalesmanager-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - ldevsalesmanager
networks:
    ldevsalesmanager:
        driver: bridge